# Generated by Django 3.1.7 on 2021-03-08 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cnpj_dap', models.CharField(blank=True, max_length=14, verbose_name='CNPJ OU DAP')),
                ('Setor', models.CharField(choices=[('A', 'Agronegócio'), ('C', 'Comércio'), ('I', 'Indústria'), ('S', 'Serviço')], max_length=1)),
                ('razao', models.CharField(blank=True, max_length=40, verbose_name='Razão Social')),
                ('endereço', models.CharField(max_length=50)),
                ('celular', models.CharField(blank=True, max_length=13)),
                ('email', models.EmailField(max_length=254)),
                ('data_abertura', models.DateField(verbose_name='Data de Abertura')),
                ('tipo_empresa', models.CharField(choices=[('EMC', 'Empresa Com CNPJ'), ('PRD', 'Produtor Rural DAP')], max_length=3, verbose_name='Tipo de Empresa')),
            ],
        ),
        migrations.CreateModel(
            name='Participante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nome', models.CharField(blank=True, max_length=100, verbose_name='Nome Completo')),
                ('cpf', models.CharField(blank=True, max_length=11, verbose_name='CPF')),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino')], max_length=1)),
                ('nascimento', models.DateField(blank=True)),
                ('Endereço', models.CharField(max_length=50)),
                ('Celular', models.CharField(blank=True, max_length=13)),
                ('Email', models.EmailField(max_length=254)),
                ('Cep', models.CharField(max_length=8, verbose_name='CPF')),
                ('Cidade', models.CharField(max_length=30)),
                ('Escolaridade', models.CharField(choices=[('FC', 'Fundamental Completo'), ('FI', 'Fundamental Incompleto'), ('MC', 'Médio Completo'), ('MI', 'Médio Incompleto'), ('SC', 'Superior Completo'), ('SI', 'Superior Incompleto'), ('PG', 'Pós Graduação'), ('SF', 'Sem Formação')], max_length=2)),
            ],
        ),
    ]
