# Generated by Django 3.1.7 on 2021-03-08 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='participante',
            name='termo',
            field=models.FileField(blank=True, upload_to='', verbose_name='termo de compromisso'),
        ),
    ]
